[project]
name = "python_examples"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "cryptography>=50.0.0",
    "numpy==2.5.2",
    "ruff==0.16.3",
    "stegano==3.0.0",
    "sympy>=1.14.0",
    "textblob==0.20.1",
]

[tool.basedpyright]
reportUnusedCallResult = "none"
reportAny = "none"
reportGeneralTypeIssues = "none"
